### ISSUE TITLE
Request for new component to deliver a Post-Purchase Survey

### ISSUE THREAD

**Issue by stejo74** [Shopify/shop-minis-ui-extensions#17]
### Component Name

FixedOptionSurvey

### Description

This component is initially intended for use on the ORDER_CONFIRMATION_PAGE to deliver a post-purchase survey question.

It will present a scrollable list of fixed response answers (similar to the ToggleButton component) for the customer to select as their answer to the survey question.

Each top level fixed response answer could also have a sub-set of fixed response answers (again using something like the ToggleButton component)to allow the customer to drill down and select a more specific answer to the question.

We would need the ToggleButton component to visually indicate that it has a set of sub-options. If a top level fixed response answer is selected and it has a sub-set of fixed response answers, then the sub-set of answers would be shown within a BottomSheet modal / useSheet hook that contains a Submit button and a cancel/back icon.

Another type of top level fixed response answer would be an 'Other' option. When selected, the 'Other' survey answer option would trigger the  BottomSheet modal / useSheet hook and would allow a customer to type their own response to the question within a TextArea input field. The  BottomSheet modal / useSheet hook would also contain a Submit button and a cancel/back icon.

### Use Cases

This component can be used to present a question and deliver a fixed set of answers and sub-set of answers for the customer to choose from. 

It's main use is for merchants to collect valuable zero-party data feedback from customers/visitors on any aspect of their business. From gaining insight into customer attribution to monitoring customer satisfaction, surveys that offer a sub-set of potential answers can be a valuable tool for merchants to improve their business.

Our initial use of this component will be to deliver a post-purchase survey question on the ORDER_CONFIRMATION_PAGE.

### Design Mockups

We have put together a short recording of how we envisage this component - https://share.zight.com/WnuWAoZe

### Key Features

I think we've covered most of the functionality and features in the Description, but as an overview, the proposed component will predominantly use existing SDK components. The area we feel may need new or adapted SDK components is on the ToggleButton to indicate when there are a sub-set of answers behind a particular option. 

This would require a chevron icon to be shown on the right-hand side of the ToggleButton.

### Dependencies

- BottomSheet Modal / useSheet Hook
- Box
- Button
- Divider
- Icon
- IconButton
- Text
- TextField
- ToggleButton (possibly MultipleChoice)

### Additional Notes

Ideally we'd like to be able to bring this component to other entry point locations in due course.

Very open to suggestions based on any limitations to this proposed component.

Thanks!

**Comment by aliibrahim** [comment]
Hi @stejo74,

Thank you for your request for a new component! I'm happy to inform you that we've recently added a post-purchase survey component called `SurveyComponent`, which you can find [here](https://github.com/Shopify/shop-minis-ui-extensions/tree/main/packages/shop-minis-ui-extensions/src/extensions/survey-single-response). This should help you achieve the use case you mentioned.

Additionally, I recommend checking out this tutorial [here](https://shop.app/minis/docs/build-a-shop-mini/build-post-purchase-survey/), as it provides detailed instructions on how to utilize this component to create a post-purchase survey Mini.

If you're looking to include a custom answer option with an "Other" selection, you can easily do this by opening the mini viewer and using the TextField components available in our SDK.

Feel free to reach out if you have any questions—we're here to help! 

Looking forward to seeing what you create!

**Comment by stejo74** [comment]
Thanks @aliibrahim, 

perfect, will do!
